name: submission-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn
      - pandas
      - numpy
      - matplotlib
      - seaborn
      - dagshub